version: "3.3"
services:
  contenta:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: contenta:dev
    environment:
      MYSQL_HOST: db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - 8080:8080
    volumes:
      - .:/contenta
    working_dir: /contenta
    stdin_open: true
    tty: true
    entrypoint: bash
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test

